### ISSUE TITLE
Missing SPDX file :-)

### ISSUE THREAD

**Issue by stcroppe** [spdx/tools#107]
Just as the cobbler forgets to repair his own shoes, most SPDX sponsored projects seem to be missing an SPDX desciption file for the project.

Need an SPDX file (files?) unless you think the SPDXParser.spdx file covers this though it isn’t intuitive. Would think an SPDX folder might work or standard naming (project.spdx, package.spdx) something to describe scope of applicability?

**Comment by wking** [comment]
On Tue, Aug 08, 2017 at 10:51:17PM -0700, stcroppe wrote:
> Need an SPDX file (files?) unless you think the SPDXParser.spdx file
> covers this…

In benbalter/licensee#85, @david-a-wheeler suggested LICENSE.spdx, and
that seems like a good choice to me.

> Would think an SPDX folder might work or standard naming
> (project.spdx, package.spdx)…

The spec also uses package.spdx in an example [1], so I think that
would be a good choice as well.

[1]: https://spdx.org/spdx-specification-21-web-version#h.2p2csry

**Comment by goneall** [comment]
SPDXParser.spdx is indeed an SPDX file for this project.  It is a bit out of date.  I'll update it it on the next release and rename it to package.spdx as suggested.  I'll leave this issue open until the changes are made.

BTW - on my long list of todo's is to use Anna's github spdx project to generate the SPDX document using a Maven plugin on code checkins.  It may take a while to get this operational since I need to setup and host a server and update the build process to support it.

**Comment by david-a-wheeler** [comment]
I think LICENSE.spdx is the better name. Many tools and documents already say that files named LICENSE are special.

**Comment by goneall** [comment]
I would like to bring this to SPDX tech team mailing list to get some additional feedback before renaming the file.

I'm assuming this is a discussion for a best practice for naming SPDX files within a repository (as opposed to naming SPDX files for a tool output or on a listing of SPDX documents in some external folder or website).

Current options:
- LICENSE.spdx
- package.spdx
- project.spdx
- [packagename].spdx (where [packagename] is the name of the package

Let me know if you would like to alter/add to the scope or options.

**Comment by silverhook** [comment]
I very much like the `LICENSE.spdx` option as well – it pops out, is more descriptive than other suggestions, and as @david-a-wheeler mentions, it looks like something both a human (or a tool) would be looking for.

The only downside I can see is that SPDX contains also technical info and maybe in the future those will be as interesting as the legal info stored in the same file.

**Comment by tsteenbe** [comment]
I am +1 for using `LICENSE.spdx`, it's already challenging to get devs to add a `LICENSE` to their project. To maximize the adoption of SPDX I believe `LICENSE.spdx` is easy to explain as human and machine readable version of `LICENSE` a.k.a v2.0 of `LICENSE`.  Opened similar ticket (https://github.com/spdx/spdx-spec/issues/19) for the SPDX specification repository

**Comment by jonasob** [comment]
`LICENSE.spdx` is also what we recommend for REUSE compliance https://reuse.software/ and seems sensible considering the primary use.

**Comment by wking** [comment]
> I would like to bring this to SPDX tech team mailing list to get some additional feedback before renaming the file.

Linkin [that thread][1], which was pretty quiet.

[1]: https://lists.spdx.org/pipermail/spdx-tech/2017-August/003386.html

**Comment by wking** [comment]
Closable with e6eed31892cbe in master?

**Comment by goneall** [comment]
Agreed.

**Comment by stcroppe** [comment]
Good decision. :-)
