### ISSUE TITLE
Test license matching against more than one instance

### ISSUE THREAD

**Issue by wking** [spdx/tools#109]
In [this comment][1], @goneall pointed at [`LicenseRDFAGenerator.java`][2] as a way to test our license-matching against known-sufficient instances of each license's text (maybe [here][3]?  My Java is weak).  However, a single test case is insufficient to exercise conditional inclusions like the new XML `<alt …>` and `<optional>` sections.  I'd rather see a corpus of known license instances (e.g. `BSD-2-Clause/good/basic.txt`, `BSD-2-Clause/good/altered-copyright-holder.txt`, `BSD-2-Clause/bad/additional-condition.txt`, …) to ensure we successfully match license instances that those short identifiers are intended to correspond to.  That way we know that the `<alt …>`, `<optional>`, etc. markup and the spec's matching guidelines are as broad (or narrow) as the legal team expects them to be.

[1]: https://github.com/spdx/license-list-XML/pull/411#issuecomment-329643759
[2]: https://github.com/spdx/tools/blob/v2.1.6/src/org/spdx/tools/LicenseRDFAGenerator.java
[3]: https://github.com/spdx/tools/blob/v2.1.6/src/org/spdx/tools/LicenseRDFAGenerator.java#L509

**Comment by goneall** [comment]
Agree this would be helpful.  I will plan on modifying the LicenseRDFAGenerator.java to test against more than one license.  Creating the test license texts is a much larger task - I'll setup a test directory where we can take contributions for licenses to be tested.  I'm thinking we could have some type of naming convention like [license-id]_[testId].txt where [license-id] would be the SPDX license ID and the testId is a string indicating what is being tested.  I'll populate the list with the license texts from the current license list with the names [license-id]_prexml.txt.

**Comment by wking** [comment]
On Fri, Sep 15, 2017 at 03:09:03PM +0000, goneall wrote:
> Creating the test license texts is a much larger task - I'll setup a
> test directory where we can take contributions for licenses to be
> tested.

I suggest this happen in a new repo, where the legal team and other
interested parties can contribute without being distracted by
surrounding Java.  It also makes the corpus easily available to other
tools that wish to test their matching implementations.

> I'm thinking we could have some type of naming convention like
> [license-id]_[testId].txt where [license-id] would be the SPDX
> license ID and the testId is a string indicating what is being
> tested.

I prefer my {license-id}/(good|bad)/{test-id}.txt [1], because:

* Using per-license directories reduces the size of the root
  directory, which would otherwise be pretty large.

* Using a good/bad layer allows to you test both matches and
  non-matches.  If you only test matches, a tool that always answers
  “Does this text match {license-id}?” with “yes” would pass.  Tools
  that answer “What license is this text?” would have to be a bit more
  complex to pass, but having bad checks still helps them by giving
  room for test text that is closer to the matching license (but not
  close enough to match) than the good text for other licenses.

We may also want an additional layer for testing matches of the
Standard License Header [2] in various contexts (e.g. a C file with
wrapping /*…*/, prefixed //, etc.; shell file with prefixed #; etc.).
That could happen as a second phase, but we may want to prepare for it
with a tempate like:

  {license-id}/(license|header)/(good|bad)/{test-id}.txt

[1]: https://github.com/spdx/tools/issues/109#issue-257929983
[2]: https://spdx.org/spdx-license-list/license-list-overview

**Comment by goneall** [comment]
@wking Excellent suggestions.  Agree with all points.  @jmanbeck has already created a repository with test files for testing license scanners: https://github.com/spdx/license-test-files

We can add a directory for the full license file text tests in your suggested formats and update the README to reflect the new test files.

It is a bit more work for the tools (I need to add the git checkout code), so it may take a little longer to implement - but I feel it is worth it to make life easier for the submitters of test files.

**Comment by wking** [comment]
> It is a bit more work for the tools (I need to add the git checkout code)...

You can use subtre merges and/or submodules for this.  I'm happy to help setup either approach.

**Comment by goneall** [comment]
Added testing in commit 7e4de292700d84714d6d05a1a3310b9f26ccb1dc
