### ISSUE TITLE
Utilize the OSI API's to automatically populate the isOsiApproved flag in the listed license

### ISSUE THREAD

**Issue by goneall** [spdx/tools#111]
https://api.opensource.org/licenses/  can access the SPDX license ID and OSI status.  This can be used to do one of the following:
1.  Fill in the OSI approved text on spdx.org/licenses based on JavaScript and real time access to the OSI API and deprecate the isOsiApproved attribute in the license list XML
2.  Set the value for osiApproved in the listed licenses based on the OSI API information at the time the license list is generated and deprecate the isOsiApproved attribute in the license list XML
3. Continue to use the isOsiApproved attribute in the license list XML, but generate a warning if the OSI API does not agree with the isOsiApproved XML attribute value.

**Comment by goneall** [comment]
Suggested by @wking on [SPDX tech email dist. list](https://lists.spdx.org/pipermail/spdx-legal/2017-October/002287.html)

**Comment by goneall** [comment]
My current preference is solution #2 since #1 depends on the OSI API site being available.  The frequency of license updates should be sufficient to keep things in sync.

**Comment by wking** [comment]
On Fri, Oct 13, 2017 at 09:20:56PM +0000, goneall wrote:
> https://api.opensource.org/licenses/ can access the SPDX license ID
> and OSI status.

The API is backed by OpenSourceOrg/licenses, and there's still a
non-canonical warning up there [1].  See also
OpenSourceOrg/licenses#47.  Hopefully serious SPDX interest (and
assistance?  I have some open PRs over there) will encourage them to
push through to something authoritative.

> 1. Fill in the OSI approved text on spdx.org/licenses based on
>    JavaScript and real time access to the OSI API and deprecate the
>    isOsiApproved attribute in the license list XML

I like this way for public HTML, although I think we'll want to go
with (2) if we distribute text/plain or similar versions of the list.
While there is a risk that the OSI site could go down, I'm fine just
telling consumers that the site is down.  With the JavaScript
approach, you wouldn't have to update the vOld page as the OSI
approves new licenses.

But if we plan on periodically rebuilding pages for all versions of
the license list to pick up new approvals, then baking the approval
status into the built pages is fine.

[1]: https://github.com/OpenSourceOrg/licenses/tree/f7ff223f9694ca0d5114fc82e43c74b5c5087891#is-this-authoritative

**Comment by goneall** [comment]
Moved to https://github.com/spdx/LicenseListPublisher/issues/20
