### ISSUE TITLE
Link to third-party pages from license list

### ISSUE THREAD

**Issue by wking** [spdx/tools#117]
This is not critical, and it would require API extentions, but it would make it easier for users to audit our assertions and/or discover additional details if the “FSF Free/Libre?” and “OSI Approved?” entries in `resources/htmlTemplate/TocHTMLTemplate.html` were also links to the third-party page.  For example, if the MIT entries linked to https://www.gnu.org/licenses/license-list.html#Expat and https://opensource.org/licenses/MIT:

| Full name | Identifier | FSF Free/Libre? | OSI Approved? | Text |
| -- | -- | -- | -- | -- |
| [MIT License](https://spdx.org/licenses/MIT.html) | `MIT` | [Y](https://www.gnu.org/licenses/license-list.html#Expat) | [Y](https://opensource.org/licenses/MIT) | [License Text](https://spdx.org/licenses/preview/MIT.html#licenseText) |

Definitely not something to block a release on or anything, but if someone has the time to work this up, I think it would be a useful improvement.

**Comment by goneall** [comment]
This would be a bit of work - I'll can look into after the next release of the license list (which is keeping me pretty busy).

If anyone else wants to take this on - feel free, I can help provide pointers to the existing implementations

**Comment by goneall** [comment]
Moved to https://github.com/spdx/LicenseListPublisher/issues/19
