### ISSUE TITLE
Consistent header/value for license-list “Text” column

### ISSUE THREAD

**Issue by wking** [spdx/tools#118]
And as a very minor nit for `resources/htmlTemplate/TocHTMLTemplate.html`, it's a bit strange to have a “Text” header on a column where all the values are “License Text”.  If “Text” is sufficient, why not use that everywhere?  If “Text” is not sufficient, why not use “License Text” in the header?  I'm also fine dropping this column entirely, because the license name already links to the per-license page, and few of our licenses have so many notes and such that that the text is hard to find there ;).

**Comment by goneall** [comment]
@jlovejoy I'll leave the TOC format questions to you - let us know if you want any modifications as suggested by @wking   The template can also be updated through a PR: https://github.com/spdx/tools/blob/722d95784f55b3923ed0428c4abf2fc915eb2b2e/resources/htmlTemplate/TocHTMLTemplate.html#L162

**Comment by goneall** [comment]
Moved to https://github.com/spdx/LicenseListPublisher/issues/18
