### ISSUE TITLE
Show regexp in HTML output for replacable text

### ISSUE THREAD

**Issue by wking** [spdx/tools#120]
[`formatReplaceabledHTML`][1] currently sets `class="replacable-license-text"`.  I think we should also set `title="match-regexp"` or something so users can mouse over (if they have a mouse) to see the replacement regexp.  Raw regexps aren't the greatest UX, but [that's what we've been using so far][2], and I can't think of anything better.

Spun off from [here][3].

[1]: https://github.com/spdx/tools/blob/d8ef31bf86099dd700555e9d173719a6478b2c46/src/org/spdx/licenseTemplate/HtmlTemplateOutputHandler.java#L93-L113
[2]: https://github.com/spdx/spdx-spec/blame/cfa1b9d08903befdf03e669da6472707b7b60cb9/chapters/appendix-II-license-matching-guidelines-and-templates.md#L28
[3]: https://github.com/spdx/license-list-XML/pull/489#discussion_r153291051

**Comment by goneall** [comment]
@wking any thoughts on how to handle the empty "original text" case?

This may be a separate issue, but currently there is no hint at all that there is variable text if the original is left out or blank.

@jlovejoy Any thoughts on including a mouse over for the var text to describe the var using a regular expression?

**Comment by wking** [comment]
> This may be a separate issue, but currently there is no hint at all that there is variable text if the original is left out or blank.

Oh, good point.  I think that's an argument for using a variable-text icon/glyph.  To open or close the variable-text region.  That solves the “how do we show the regexp (or whatever) to touch users?” issue and the “what do we do when the `<alt>` has no content?” issue.

**Comment by goneall** [comment]
>  I think that's an argument for using a variable-text icon/glyph to open or close the variable-text region. 

I like the proposal.  Especially if we open and close the text region.

Unfortunately, this is beyond my HTML skills.  Is this something that could be included in the style or does it have to be inline HTML?

If inline HTML, I could include it in the Java code if someone attaches a sample.

**Comment by wking** [comment]
On Mon, Nov 27, 2017 at 07:50:00PM +0000, goneall wrote:
> Is this something that could be included in the style or does it
> have to be inline HTML?

I've mocked something up at [1], which is primarily using CSS with a
<span> placeholder wherever you want the icon.  That ensures the icon
is not going to be copy/pasted from a rendering of the HTML.  I've
used ☿ for the icon, but I didn't hunt around too hard.  Anything that
gets “this might change” across and won't be mistaken for the license
text itself would work.

[1]: http://tremily.us/var-match.html

**Comment by goneall** [comment]
Moved to https://github.com/spdx/LicenseListPublisher/issues/17
