### ISSUE TITLE
Update to new fsf-api format with arrays of SPDX identifiers

### ISSUE THREAD

**Issue by wking** [spdx/tools#141]
Catch the tooling here up with wking/fsf-api#9.  This isn't a high priority, because you [vendor the full JSON][1].  But you'll need it if you want [the list][2] to mark `GPL-3.0-only` and similar as FSF libre.

[1]: https://github.com/spdx/tools/blob/636cd7f77cd9b0b367b566b4d474f8713e9d9d02/resources/licenses-full.json
[2]: https://spdx.org/licenses/

**Comment by goneall** [comment]
Once the wking/fsf-api#9 is merged, I'll update the tools.

The tool will use RDF libraries to read the github.io pages generated by wking/fsf-api.

If the files are offline, it will use a local cache of the licenses-full.json that has been modified to include a local copy of the schema files such that it would work offline.

**Comment by goneall** [comment]
Moved the issue to LicenseListPublisher: https://github.com/spdx/LicenseListPublisher/issues/8
