### ISSUE TITLE
Invalid SPDX 2.1 Examples

### ISSUE THREAD

**Issue by stevespringett** [spdx/tools#142]
The SPDX 2.1 RDF and Tag examples are invalid according to version 2.1.7 of SPDX tools.

```bash
java -jar spdx-tools-2.1.7-jar-with-dependencies.jar Verify SPDXRdfExample-v2.1.rdf 
This SPDX Document is not valid due to:
	Missing required copyright text for Saxon in Saxon
```

```bash
java -jar spdx-tools-2.1.7-jar-with-dependencies.jar Verify SPDXTagExample-v2.1.spdx
This SPDX Document is not valid due to:
	Relationship at line 97 invalid: Missing required copyright text for Saxon in Saxon
	Package at line 169 invalid: Missing required copyright text for Saxon in Saxon
```

v2.0 of each of the examples validates successfully.

**Comment by stevespringett** [comment]
Relates to #108

**Comment by goneall** [comment]
@stevespringett Thanks for catching this!  I just pushed fixes to the master branch.  I also added unit tests to make sure future examples all parse without warnings.

I'll be pushing out a new release by Jan 15 which will include the corrected examples.

**Comment by stevespringett** [comment]
Fantastic! Appreciate the fast turn-around.
