### ISSUE TITLE
/licenses/licenses.json: All isDeprecatedLicenseId properties are false

### ISSUE THREAD

**Issue by kemitchell** [spdx/tools#144]
Requesting <https://spdx.org/licenses/licenses.json>, I receive JSON that sets `isDeprecatedLicenseId` to `false` for each object. For example, for old `GPL-2.0`:

```json
{
"reference": "./GPL-2.0.html",
"isDeprecatedLicenseId": false,
"isFsfLibre": false,
"detailsUrl": "http://spdx.org/licenses/GPL-2.0.json",
"referenceNumber": "356",
"name": "GNU General Public License v2.0 only",
"licenseId": "GPL-2.0",
"seeAlso": [
"http://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html",
"http://www.opensource.org/licenses/GPL-2.0"
],
"isOsiApproved": true
}
```
The top-level `licenseListVersion` property is `"3.0"`.

Thanks!

**Comment by wking** [comment]
On Tue, Jan 09, 2018 at 05:23:39PM +0000, Kyle Mitchell wrote:
> Requesting <https://spdx.org/licenses/licenses.json>, I receive JSON
> that sets `isDeprecatedLicenseId` to `false` for each object. For
> example, for old `GPL-2.0`:
> 
> ```json
> {
> "reference": "./GPL-2.0.html",
> "isDeprecatedLicenseId": false,

This should be fixed.  Luckily license-list-data doesn't have this
problem [1], although I don't see an equivalent to licenses.json (with
all the licenses) there.

[1]: https://github.com/spdx/license-list-data/blob/v3.0/json/details/GPL-2.0.json

**Comment by kemitchell** [comment]
@goneall, is the plan to deprecate <https://spdx.org/licenses/licenses.json> in favor of spdx/license-list-data, or is there somewhere we can patch to bring the two in sync?

**Comment by goneall** [comment]
> is the plan to deprecate https://spdx.org/licenses/licenses.json in favor of spdx/license-list-data, or is there somewhere we can patch to bring the two in sync?

Keep the two in sync (mostly).  The medium term plan is to update the website on every release.  The license-list-data will be updated more frequently.  On release, the license-list-data repo will be tagged with the release version.  If you are using the license-list-data repo, suggest using a the tagged release rather than the master since it will be more stable.

BTW - found the problem - as @wking mentioned above, it is local to the website version of the JSON file.  I'll upload a new JSON file to the website in the next hour or so.

**Comment by wking** [comment]
On Tue, Jan 09, 2018 at 07:47:06PM +0000, goneall wrote:
> … as @wking mentioned above, it is local to the website version of
> the JSON file.

Are there plans to have a licenses.json in license-list-data?  A list
of some sort seems like a useful part of the JSON API, and it would be
good to be able to grab that data with per-list-release granularity
(at least, for future tags).

**Comment by goneall** [comment]
Just pushed a fix for the tool and replaced the licenses.json file on the website with a corrected version.

**Comment by goneall** [comment]
> Are there plans to have a licenses.json in license-list-data?  

There is a licenses.json at https://github.com/spdx/license-list-data/blob/master/json/licenses.json

**Comment by wking** [comment]
On Tue, Jan 09, 2018 at 08:48:55PM +0000, goneall wrote:
> > Are there plans to have a licenses.json in license-list-data?  
>
> There is a licenses.json at
> https://github.com/spdx/license-list-data/blob/master/json/licenses.json

Oops.  Looks like my local checkout was missing some files ;).  Should
have double-checked GitHub.

I'm not clear on how that file missed being affected by the bug fixed
in a487dfc4688 (maybe just a different code path?), but the
website/licenses.json file does seem to have been affected [1].  I'm
not sure how that fits into our release strategy.  Do we want a new
build of the 3.0 licence-list-XML (not master, which now includes
spdx/license-list-XML#590) which would be tagged in license-list-data
as 3.0.1?

[1]: https://github.com/spdx/license-list-data/blob/v3.0/website/licenses.json#L4464

**Comment by goneall** [comment]
> I'm not clear on how that file missed being affected by the bug 

Slightly different code path.   About 90% of the code is comment, the bug was in the 10% that is different for the website.

> Do we want a new build of the 3.0 licence-list-XML

There should only be the one file different (website/licenses.json).  I can commit the change to license-list-data.  Should we tag it as v3.0.1 or just move the 3.0 tag to include this change?

**Comment by wking** [comment]
On Tue, Jan 09, 2018 at 01:56:25PM -0800, goneall wrote:
> > Do we want a new build of the 3.0 licence-list-XML
>
> There should only be the one file different (website/licenses.json).
> I can commit the change to license-list-data.  Should we tag it as
> v3.0.1 or just move the 3.0 tag to include this change?

I'd really rather not move tags.  Is this something that should be
decided on the tech list, or is this issue visible enough?

We'll also need a spdx/tools release if we want to handle
auto-publishing (spdx/license-list-XML#592,
spdx/license-list-data#22).

**Comment by wking** [comment]
Auditing `website/licenses.json` with:

```console
license-list-data $ diff -u <(git cat-file -p v2.6:website/licenses.json | jq -S '.licenses | sort_by(.licenseId) | [.[] | del(.referenceNumber) | del(.seeAlso)]') <(git cat-file -p v3.0:website/licenses.json | jq -S '.licenses | sort_by(.licenseId) | [.[] | del(.referenceNumber) | del(.isFsfLibre) | del(.seeAlso)]')
```

turned up this issue and spdx/license-list-XML#595 as the only significant changes (that I noticed).  There are also some insignificant changes to `referenceNumber` (ignored above, spdx/license-list-data#23).  I'm ignoring the new-in-3.0 `.isFsfLibre` (no 2.6 data to compare it to).  And I'm ignoring `.seeAlso` (not a fundamental license property).

I skimmed over the new-in-3.0 licenses; just comparing changes in our markup for licenses which were part of 2.6.

And that `diff` is just looking at the material in `website/licenses.json` (which doesn't include the matching template, standard header, etc.).

**Comment by goneall** [comment]
> I'd really rather not move tags.  Is this something that should be decided on the tech list, or is this issue visible enough?

The change is only to the website subdirectory.  Since most people are accessing the JSON data from the JSON subdirectory, I don't think we need to worry about the tagging for this issue.

**Comment by goneall** [comment]
> We'll also need a spdx/tools release if we want to handle auto-publishing

Once the FSF API's are stable (e.g. [Pull Request 12](https://github.com/wking/fsf-api/pull/12) is merged), I'll update the tools and push out a new release.

**Comment by wking** [comment]
> The change is only to the website subdirectory.

If subsets of the repository are not covered by tag stability, they should probably be called out in the docs.  Or maybe moved to a separate repository?
