### ISSUE TITLE
Provide a non-RDFa RDF Readable format for license files on spdx.org/licenses

### ISSUE THREAD

**Issue by goneall** [spdx/tools#146]
To resolve issue #90 and help with issue #145, I would like to remove the RDFa dependency from the SPDX tools.

RDFa is currently used to read the license information from spdx.org/licenses.

An additional format could be added to the website which is machine readable and more efficiently parsed by the tools.

There are several formats to choose from:

1.  RDF/XML
2. JSON-LD with contexts embedded in the JSON files as separate files from the current .json files
3. JSON-LD by adding contexts to the current JSON files
4. JSON-LD by adding a reference to an context file
5. RDF Turtle
6. Some other RDF format
7. any permutation of the above choices

I'm leaning towards 3 as long as it doesn't break compatibility with existing uses of JSON files.  Option 4 would be cleaner and more compact, but would require the SPDX tools always be connected to the internet to run.

@kemitchell @yevster @wking thoughts?

**Comment by wking** [comment]
On Wed, Jan 10, 2018 at 11:20:40AM -0800, goneall wrote:
> Option 4 would be cleaner and more compact, but would require the
> SPDX tools always be connected to the internet to run.

Option 4 would not require an internet connection if you use a
relative URI for the @schema value.

**Comment by goneall** [comment]
> Option 4 would not require an internet connection if you use a relative URI for the @schema value.

Good point, in which case option 4 would be a better approach IMHO

**Comment by goneall** [comment]
Having a difficult time convincing the Jena library to use an external context file, so decided to go with option number 3 for now.  Since we are using a library that reads both internal and external contexts, the SPDX tools code is the same for option 3 and 4.  We can update the LicenseListPublisher in the future to generate files with an external context.

**Comment by goneall** [comment]
Resolved in version 2.1.12 - I'll revisit the external context in the 3.0 timeframe
