### ISSUE TITLE
Unexpected error reading the HTML template: resources\htmlTemplate does not exist

### ISSUE THREAD

**Issue by vcmgc27** [spdx/tools#156]
Getting this unexpected error when trying to execute RdfToHtml function.

Below is the details:
C:\BD_Docs\OSS_Papers\SPDX>java -jar spdx-tools-2.1.7-jar-with-dependencies.jar RdfToHtml ./test.rdf ./testhtml.html
log4j:WARN No appenders could be found for logger (Jena).
log4j:WARN Please initialize the log4j system properly.
Unexpected error reading the HTML template: resources\htmlTemplate does not exist

Version used is 2.1.11

Help in resolving this issue

Thanks,
vcmgc

**Comment by goneall** [comment]
Check to see if there is a resources subdirectory in the directory where the java tools jar file is located.

I'll attach a zip file with the directory to this issue.  If you don't find the resources directory, unarchive the attached.
[resources.zip](https://github.com/spdx/tools/files/1884344/resources.zip)

**Comment by vcmgc27** [comment]
Hi,

Will try this out and let you know.

Thanks,
vcmgc

**Comment by vcmgc27** [comment]
Hi,

Can you get me a new version of jar file with the latest updates.

Thanks,
Gowtham C

**Comment by goneall** [comment]
> Can you get me a new version of jar file with the latest updates.

There are a couple of bugs I want to fix before the next release - shouldn't take me more than a couple of days.

You should be able to install the resource files attached above to resolve this issue.  Let me know if that works - I want to make sure I don't need another fix before spinning a release.

**Comment by goneall** [comment]
Just released a new version 2.1.12 which includes all the latest.
