### ISSUE TITLE
Update json-simple

### ISSUE THREAD

**Issue by grv87** [spdx/tools#163]
This project uses old version of `com.googlecode.json-simple:json-simple` library.
This version has a bunch of issues, including unnecessary JUnit dependency: fangyidong/json-simple/issues/91.

I propose you to use more recent fork: https://github.com/cliftonlabs/json-simple. Which fixed this and a lot of other issues.

**Comment by goneall** [comment]
@grv87 Thanks for pointing this out.  Moving to the cliftonlabs version seems reasonable.  We could also address the issue on Junit by adding an exclusion to the POM file.  @yevster  - any opinions on the approach?

**Comment by goneall** [comment]
@grv87 In my dev environment, I changed to the latest published version of the cliftonlabs json-simple.  I ran into a number of compile failures requiring changes beyond just updating the import statements.  It's going to require a bit of time to analyze, change the names of some of the classes / methods and any other required changes.

I won't be able to spend much time on this over the next month, but if you want to make the changes and create a PR, I can review and merge.

**Comment by grv87** [comment]
@goneall,
Only 2.* version of cliftonlabs's fork is claimed to be compatible.
Latest (3+) is not, there were breaking changes.
You really want to update to latest? Why not just use last version from 2.+ series?

**Comment by goneall** [comment]
@grv87 I'll try using the latest 2. version

**Comment by goneall** [comment]
@grv87 Version 2.3.1 worked.  The changes are merged into the master branch.  Let me know if you need a release spun for this change.  Otherwise, I'll probably do another release in 2-3 months.

**Comment by goneall** [comment]
I just pushed out a release 2.1.15 which resolves this issue
