### ISSUE TITLE
artefacts are now published in maven central repository

### ISSUE THREAD

**Issue by oupala** [spdx/tools#171]
It appears that some artefacts are now published in maven central repository:

https://github.com/spdx/tools/blob/7c4a67fba02d3a220c71101845c206121fc3e9f1/pom.xml#L47-L52

- [apache-jena-lib](https://search.maven.org/search?q=g:org.apache.jena%20AND%20a:apache-jena-libs&core=gav) is available in version [3.1.1](https://search.maven.org/artifact/org.apache.jena/apache-jena-libs/3.1.1/pom)
- [apache-jena-iri](https://search.maven.org/search?q=g:org.apache.jena%20AND%20a:jena-iri&core=gav) is available in version [3.1.1](https://search.maven.org/artifact/org.apache.jena/jena-iri/3.1.1/jar)

It's maybe time to update the pom.xml of spdx-tools.

**Comment by goneall** [comment]
@oupala Thanks for pointing this out.  I just updated the POM file on both the master branch and the yamlsupport branches.

**Comment by oupala** [comment]
How is maven central updated from this new release? The last version of spdx-tools in maven central is still [version 2.1.12, of 14-Apr-2018](https://search.maven.org/search?q=g:org.spdx%20AND%20a:spdx-tools&core=gav).

**Comment by goneall** [comment]
The release is published to bintray.  The releases need to be manually sync'd with maven central (which I forgot to do).

I just sync'd both the spdx-tools and the license list publisher.  It should show up within a couple hours.

**Comment by oupala** [comment]
Ok, I can see the new release 2.1.13 in [Maven Central](https://search.maven.org/search?q=spdx).
