### ISSUE TITLE
useless JBoss 3rd-party repository?

### ISSUE THREAD

**Issue by oupala** [spdx/tools#175]
Is the JBoss 3rd-party repository useless?

https://github.com/spdx/tools/blob/f1a114070ebde6cf6a94bdb08d6303a47f41eadb/pom.xml#L51-L54

I couldn't find any dependency retrieved from this repository.

If it is useless, it could be removed the make the pom.xml file simpler.

**Comment by goneall** [comment]
Removed in PR #176

**Comment by oupala** [comment]
It now works like a charm. Thanks!
