### ISSUE TITLE
Add descriptions for different tools in README

### ISSUE THREAD

**Issue by silverhook** [spdx/tools#183]
While the README file and the `--help` flag are already really useful, it is missing info on what the individual tools actually do.

While with `Verify` and `RdfToTag` it is quite self-explanatory, tools like `LicenseRDFAGenerator` are a mystery to a newcomer.

**Comment by silverhook** [comment]
It seems the [PDF documentation](https://spdx.org/sites/cpstandard/files/pages/files/spdx_tools-20170327.pdf) can be obtained from https://spdx.org/tools.

Perhaps a copy or link would be useful :)

**Comment by goneall** [comment]
@silverhook Thanks for pointing this out.  Some of the information looks a bit stale as well.  I'll make a pass at the documentation and update it over the next week or so.

**Comment by goneall** [comment]
Resolved with PR #184 

@silverhook if you see any other improvements for the documentation, feel free to create a PR.  The help text is at https://github.com/spdx/tools/blob/2fa4314cc14c220b0c2205a969aa9b4eed021d4a/src/org/spdx/tools/Main.java#L67

**Comment by silverhook** [comment]
Perfect, thank you @goneall :+1:
