### ISSUE TITLE
Confusing error message when duplicate license ID's are in an SPDX document

### ISSUE THREAD

**Issue by goneall** [spdx/tools#190]
When running the validator, if there are multiple license-Ref definitions with the same ID, you get the error `Error converting tag/value to RDF/XML format: Expecting a definition of a file, package, license information, or document property at LicenseId: LicenseRef-XXX ...`

The error should indicate multiple license ref's were found.

**Comment by goneall** [comment]
I'm no longer able to reproduce this issue - @nishakm, do you still have the original SPDX file that caused this bad error message?

**Comment by nishakm** [comment]
> I'm no longer able to reproduce this issue - @nishakm, do you still have the original SPDX file that caused this bad error message?

@rnjudge might be able to reproduce the SPDX file

**Comment by goneall** [comment]
Closing this issue since I am not able to reproduce the problem.

@nishakm @rnjudge if you have a file that reproduces the error, go ahead and attach and I'll re-open
