### ISSUE TITLE
Documentation for java idiots needed

### ISSUE THREAD

**Issue by CsatariGergely** [spdx/tools#218]
Documentation should describe how to compile to code and where the result is.

**Comment by goneall** [comment]
@CsatariGergely The [Development Section](https://github.com/spdx/tools#development) is admittedly a bit light.  The [Maven documentation ](http://maven.apache.org/users/index.html) provides information on how to compile and where the results are located.  Do you have any specific suggestions beyond referencing the Maven documentation?

**Comment by goneall** [comment]
Closing the issue as there are not enough specifics to action
