### ISSUE TITLE
Handle URL redirects for SPDX listed licenses

### ISSUE THREAD

**Issue by goneall** [spdx/tools#219]
If the URL for the SPDX listed licenses were to move and a URL redirect is returned, the SPDX tools will fail to redirect and use the local cache of licenses rather than follow the redirect.

The code that needs updated is located at https://github.com/spdx/tools/blob/ff853b093e6797c8aaad3c98da2ef6937f5e69fe/src/org/spdx/rdfparser/license/ListedLicenses.java#L280

**Comment by jay24rajput** [comment]
Hey! Is this issue up for grabs?

**Comment by goneall** [comment]
@goneall Yes - please feel free to take this :)
