### ISSUE TITLE
Include the link for SPDX Online Validation Tool somewhere in the README

### ISSUE THREAD

**Issue by rnjudge** [spdx/tools#228]
I could not find a link or reference to the [SPDX Online Validation tool](http://13.57.134.254/app/validate/) anywhere in the tools README or in other relevant documentation. Is there a reason this link isn't easier to find? If not, I would be happy to open a PR to add a reference for finding it.

**Comment by goneall** [comment]
@rnjudge It should be easy to find - please open a PR - Thanks!
