### ISSUE TITLE
Confusing Error message trying to validate tag value document

### ISSUE THREAD

**Issue by rnjudge** [spdx/tools#229]
I am trying to reproduce https://github.com/spdx/tools/issues/190. I generated an SPDX document from Tern (in spdxtagvalue format) using the `golang:1.14-alpine` image. When I upload the document to the online [validation tool](http://13.57.134.254/app/validate/), I get a text box that pops up. There is a red banner at the top of the box that says `Error!` and the message is:
```
net.rootdev.javardfa.jena.RDFaReader
```

I am unsure what this means or how best to proceed.

Browser: Firefox
Host OS: Ubuntu

**Comment by goneall** [comment]
There is definitely something wrong with the website - The appears to be a problem with any of the functions that work with SPDX documents.  Since the software has not been updated in some time, there must be an operational issue with the site.  I'll try restarting the server.

**Comment by goneall** [comment]
@rnjudge It looks like it is back in working order.  I submitted a related issue on the online tools code to track the bad error message: https://github.com/spdx/spdx-online-tools/issues/157
