### ISSUE TITLE
Upgrade Java to 1.7

### ISSUE THREAD

**Issue by romeara** [spdx/tools#23]
Oracle discontinued support for Java 1.6 some time ago, and will soon end support for Java 1.7. Asking all consumers to jump to Java 1.8 is (in my opinion) a bit much to ask at this time, but I'd suggest that we should try to keep it no more than one "unsupported" version of Java behind.

I'm not sure of the process required to make such a switch, so I am expecting some discussion on this issue will be required before any pull request is accepted.

**Comment by yevster** [comment]
Master moved to java 8.
