### ISSUE TITLE
Converting error due to the white space in license name

### ISSUE THREAD

**Issue by JustinWonjaePark** [spdx/tools#256]
As far as I know, white spaces are allowed (and multiple white spaces are treated as single white space) in a License Name
[Appendix II > 3. Whitespace](https://spdx.github.io/spdx-spec/appendix-II-license-matching-guidelines-and-templates/#3-whitespace)

So, I made a spreadsheet that contains license name "LicenseRef-MIT-like-License c-ares" .
And then, I tried to convert it to RDF using SPDX Tool Version: 2.2.0
(Actually I downloaded 2.2.2 but I get 2.2.0 when I ask with 'Version' option)
Now I get an error as follows.

_[main] ERROR org.spdx.spdxspreadsheet.AbstractSpreadsheet - Invalid license information in in files for license LicenseRef-MIT-like-License c-ares row 2 detail: Invalid license expression.  Expecting more operands. in PackageInfo sheet._

Please let me know if I am missing something.

**Comment by goneall** [comment]
White space is allowed in the license name, but not in the license ID.  See the [License Expressions Appendix](https://spdx.github.io/spdx-spec/appendix-IV-SPDX-license-expressions/) for the syntax on the license ID's.

**Comment by JustinWonjaePark** [comment]
Thanks @goneall !
I misunderstood concept of License Identifier and License Name.
