### ISSUE TITLE
Copyright sign in GPL-3.0 does not match all instances

### ISSUE THREAD

**Issue by spoenemann** [spdx/tools#260]
The current license template of GPL-3.0 contains the line

> Copyright © 2007 Free Software Foundation, Inc.

However, the copyright sign `©` is represented as `(C)` in many instances of the license found in the wild. The template should be able to match both variants.

**Comment by goneall** [comment]
@spoenemann Finally got this resolved in PR #261 - if you pull the latest code, it should now work.

Let me know if you want me to spin out a new release to Maven Central and Bintray

**Comment by spoenemann** [comment]
Great! It would be good to have this in a release at some time, but it's not urgent as we have a workaround.

**Comment by goneall** [comment]
Resolved in release 2.2.4
