### ISSUE TITLE
spdx-tools-jar-with-dependencies.jar missing

### ISSUE THREAD

**Issue by C1ph3R-s** [spdx/tools#262]
Is it possible that I did not found spdx-tools-jar-with-dependencies.jar file in the repo?

**Comment by goneall** [comment]
The Jar can be downloaded from here: https://bintray.com/spdx/spdx-tools/download_file?file_path=org%2Fspdx%2Fspdx-tools%2F2.2.4%2Fspdx-tools-2.2.4-jar-with-dependencies.jar

I also added the Jar file to the latest release in Github and updated the README with a pointer to the download locations.

**Comment by goneall** [comment]
Closing this issue as resolved with the updated documentation.
