### ISSUE TITLE
Eclipse Flags Compilation Errors In Existing Source

### ISSUE THREAD

**Issue by romeara** [spdx/tools#27]
Eclipse (Luna, on Windows) is flagging certain lines as invalid characters. Could anyone shed some light onto what this is supposed to be and how I get my environment to not flag it? Am I missing a character set or something?

Line is in LicenseRDFGenerator:

INVALID_FILENAME_CHARS.add('Â³'); (Line 67)

**Comment by goneall** [comment]
Check the text encoding on the project properties - it should be set to UTF-8.

**Comment by romeara** [comment]
That fixed it - it was set to Cp1252 for some reason. Thanks!
