### ISSUE TITLE
Receiving error trying to validate SBOM

### ISSUE THREAD

**Issue by rjb4standards** [spdx/tools#278]
The online validation tool is throwing an error 
The application could not be connected. Please try later.

**Comment by goneall** [comment]
@rjb4standards Thanks for reporting this.  This is a known intermittent issue that (hopefully) will be solved with the next upgrade.

I'll restart this server later today once I'm fully online.

When you run into this issue, you can try refreshing the browser - this may connect you to a different server thread that isn't stuck.

**Comment by goneall** [comment]
@rjb4standards back up and running.  Turned out we ran out of disk space, so it took a while to re-size.  Sorry about the delay.
