### ISSUE TITLE
Make license texts easily accessible

### ISSUE THREAD

**Issue by sindresorhus** [spdx/tools#3]
I currently [scrape them from the git repo and sanitize](https://github.com/sindresorhus/spdx-license-list) them. Would be easier if they were easily accessible from the official source.

**Comment by kemitchell** [comment]
Thanks, Sindre. I'll try and keep it quiet in here.

**Comment by goneall** [comment]
In addition to the license text (property name licenseText), the following fields are available in the RDF format but not yet available in JSON.  For more information on the RDFa access to the license list see the pdf document at https://spdx.org/sites/spdx/files/publications/SPDX-TR-2014-2%20v1%200.pdf

standardLicenseHeader
licenseTemplate
sameAs

**Comment by goneall** [comment]
I just uploaded the licenses.json file to spdx.org/licenses.

We plan on formally anouncing the availability of the JSON format in August.  This will give us a chance to fine tune any issues we find.  Post any issues here or send to the spdx-tech distribution list.

**Comment by kemitchell** [comment]
@shinnn, you may like to know that @goneall has just published a JSON file listing SPDX license identifiers to spdx.org, as a preview. Public announcement probably in August. Feedback welcome in the meantime!

**Comment by shinnn** [comment]
> @goneall has just published a JSON file listing SPDX license identifiers to spdx.org, as a preview

Ohhhh, great! https://spdx.org/licenses/licenses.json

**Comment by kemitchell** [comment]
@shinnn, please just remember that this is a preview. SPDX will officially announce in a couple months, after it's been tested.

**Comment by goneall** [comment]
Based on some of the email threads on spdx-tech email list, I would propose we add an additional json file for each license with all of the tags currently supported in the RDFa version.  This would allow parsing the license text as well as the license header using JSON.  The format would be [spdx-identifier].json.

An alternative proposal would be to create on really large JSON file that contained all of the licenses.  My concern on this alternative is the size of the file.  The file per license seems to work well for RDFa parsing.

**Comment by kemitchell** [comment]
@goneall many downstream consumers will want license identifiers and names only. Any chance we could generate and continue to serve, say, an `index.json` with ID, name, and URI of the more extensive per-license JSON file?

**Comment by goneall** [comment]
@kemitchell I would propose that we retain the index of all license as it is today - this would be an additional set of HTML files.  I like the idea of adding a URL for the more detailed JSON for that license.

**Comment by kemitchell** [comment]
@goneall: Sounds good to me. Just FYI, if we change the current JSON file in the wrong way, we will break new releases of the code npm and RubyGems use for validation. Patches would have to go to rubygems/rubygems. For npm, you'd want to ping me and @shinnn.

@shinnn & @sindresorhus: Happy holidays! Hope you're well.

**Comment by goneall** [comment]
@kemitchell I'll try to keep the current JSON file compatible - glad to see it is getting good use.

**Comment by goneall** [comment]
I'm now working on updating the tool that generates the spdx.org/licenses web pages.

In the spdx.org/licenses/licenses.json file I added two new fields for each license:
* detailsUrl - URL of a JSON file that has the text and detailed information for the given license
* isDeprecatedLicenseId - If a license ID is deprecated, this will be set to true

I am also adding a JSON file for each license (http://spdx.org/[license-id]).  The field names are the standard spdx property names.

Attached is an example for the MIT license.

@kemitchell @sindresorhus @shinnn Please let me know if you have any feedback on the changes.  I'll update the website within the next week or so.
[MIT.json.txt](https://github.com/spdx/tools/files/93096/MIT.json.txt)

**Comment by goneall** [comment]
The website at spdx.org/licenses have now been updated per the changes described above.

@kemitchell @sindresorhus @shinnn  - Please take a look and let me know if you see anything that should be changed.  I'll announce this to the technical team mailing list on spdx.org as a "beta" version.  I would like to target a general availability in approximately 2 weeks.

**Comment by kemitchell** [comment]
I don't see any option offhand.

**Comment by goneall** [comment]
@kemitchell  - could you clarify - did you seen any issue in the review?  Thanks.

**Comment by kemitchell** [comment]
Sorry. AutoCorrect mishap. I didn't see any issue.

I've just rerun RubyGems' script to pull the IDs from the JSON file. No issues.

LGTM

**Comment by goneall** [comment]
No issues have been reports on the details at http://spdx.org/[license-id], so I'm going to call this a "release" and close this issue.  If you see anything wrong or missing, please open up a new issue to track.  The SPDX tools will now generate the licenses.json and the detailed json file for each license on every release of the license list.

**Comment by kemitchell** [comment]
Thanks, @goneall!
