### ISSUE TITLE
Change the default GitHub branch to "develop"

### ISSUE THREAD

**Issue by kemitchell** [spdx/tools#4]
@goneall, I was very grateful for your e-mail of earlier this week pointing out that active development is currently on `develop`, not `master`.

For the benefit of anyone who wanders into the code via GitHub, might you like to change the default branch to `develop`? I've been added to @spdx/contributor, but it doesn't look like I have permissions on the repository needed to do so.

If you'd like, I will PR [a GitHub-recognized CONTRIBUTING file](https://github.com/blog/1184-contributing-guidelines) making clear that coders should PR from topic branches off `develop` and give notice in PR comments that they license contributions per Apache-2.0.

**Comment by goneall** [comment]
Good point - I went ahead and switched the default to develop.

If you could take care of a CONTRIBUTING file for the license contributions per Apache, that would be helpful.

I'm hoping to merge everything back to master within the next week or so.  The develop branch was created for the 2.0 work which was rather extensive.  Now that we're done, I'm wondering if we should move back to the simpler model of using just the master branch.

**Comment by kemitchell** [comment]
I _would_ recommend moving back to `master` as mainline. That's more or less the norm on public GitHub, and it's flow I see taught to newbies most often. Users pulling the artifact from Maven will get what they need without Git, and for anyone with an issue in a specific, older version, we have release tags.
