### ISSUE TITLE
Dependency on Java 1.7 introduced

### ISSUE THREAD

**Issue by goneall** [spdx/tools#46]
Commit cb32edbc4c2ec4c372a462188b7e26b65a93c25c "remove potential NPE occurrences"  introduced a dependency on Java version 1.7.  This should be removed until we decide to drop support for version 1.6 (currently in discussion on the SPDX tech list).

**Comment by goneall** [comment]
The dependencies are on the Java.util.Objects in the class SPDXDocument.java

**Comment by goneall** [comment]
Just pushed a fix to change the check for null in in the if statement.

Note: please change the compliance level in your IDE to Java 1.6 until we drop support for the 1.6 JRE

**Comment by romeara** [comment]
Huh - my compliance level was set to 1.6, and I had been using Guava Objects... I'll have to look into why it allowed me to import the Java 7 version

**Comment by romeara** [comment]
@goneall - Found the issue, my environment "helpfully" switching to pointing to a 1.7 JDK. Is corrected, should prevent any future introductions. Sorry for the inconvience
