### ISSUE TITLE
Add seeAlso URL's to license list JSON file

### ISSUE THREAD

**Issue by goneall** [spdx/tools#57]
I would like to add the seeAlso URL's for the listed license to the generated JSON file located at http://spdx.org/licenses/liceneses.json.  It will add some additional approx. 50% to the file size (from about 42K to 66K).

If there is any concern about compatibility or impact to existing implementations, please comment on this issue.  I plan to make the change around August 5 if no issues are raised.

Below is a snippet of the JSON file for a license with seeAlso:
{"licenseId":"AFL-1.1","isOsiApproved":true,"name":"Academic Free License v1.1","referenceNumber":"3","seeAlso":["http:\/\/opensource.linux-mirror.org\/licenses\/afl-1.1.txt"],"reference":".\/AFL-1.1.html"}

**Comment by kemitchell** [comment]
I'm not familiar with linux-mirror.org. Is the plan to provide URLs of plain text copies of the licenses?

**Comment by goneall** [comment]
Adding a bit more background/context to the enhancement.

The seeAlso property of the SPDX License List is a reference to other websites that contain the license.  A better example than the one above would be the Apache license which has a seeAlso URL of "http://www.apache.org/licenses/LICENSE-2.0".  This is an optional field with zero or more seeAlso URL references.

The reason I would like to add this is to support a Maven plugin which generates SPDX files.  In the maven plugin, I am mapping the URL's for licenses described by the Maven license property to SPDX licenses.  The current implementation fetches the RDF for each individual license from spdx.org/licenses to build the map taking several seconds (about 30) to execute each time the plugin starts up.  To solve the performance problems, I would like to generate a single file for all licenses containing the seeAlso so I only have to parse one file.

The JSON format looks like a reasonable approach since it already contains all of the information with the exception of seeAlso.  It is also easier to parse than the RDF format (the plugin would have less dependencies).

There a few alternative if the changes to the JSON format causes issues either due to the larger size or due to compatibility.  The alternatives I am currently considering include:
- Just storing the map as a file in the Maven plugin resources directory.  The problem with this approach is it would not get updated when the spdx.org/licenses site is updated.  It would require an update to the plugin.
- Add the fields to the RDFa embedded in spdx.org/licenses/index.html - This is probably my second choice.  Only downside is the additional plugin dependencies.
- Create a separate JSON file "seealsomap.json" that can be published to spdx.org/licenses containing only the license ID and seeAlso fields.  Only concern on this approach is that it is more complex than including the seeAlso in the same file as the license ID's.

**Comment by kemitchell** [comment]
The only current consumers of the JSON file on spdx.org are:

1. https://github.com/shinnn/spdx-license-ids/blob/master/build.js#L13

2. https://github.com/rubygems/rubygems/blob/master/util/generate_spdx_license_list.rb#L4

These are the libraries that feed into command-line validation for npm and RubyGems, respectively.

Both replicate `licenseId` properties exclusively. No breakage.

**Comment by goneall** [comment]
I just updated the website with a new JSON file containing the seeAlso fields.

Please open an issue if it causes any problems.
