### ISSUE TITLE
Line Endings are Not Consistent, Despite Git Settings

### ISSUE THREAD

**Issue by romeara** [spdx/tools#6]
Hi,

When trying to create a new clone of the repository ('develop' branch), I see many files already marked as changed. Some investigation leads me to believe that these files somehow got committed to the repository without the 'text=auto' gitattribute setting being applied.

This occurs on Windows and Linux (Ubuntu) machines, which is what leads me to believe that they sneaked in without the setting being applied, as opposed to the setting being wrong.

The git status output I see is:

    git status
    On branch develop
    Your branch is up-to-date with 'origin/develop'.

    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)

	    modified:   README.md
	    modified:   src/org/spdx/spdxspreadsheet/SpreadsheetException.java
	    modified:   src/org/spdx/tag/BuildDocument.java
	    modified:   src/org/spdx/tag/BuildLegacyDocument.java
	    modified:   src/org/spdx/tag/HandBuiltParser.java
	    modified:   src/org/spdx/tag/InvalidSpdxTagFileException.java
	    modified:   src/org/spdx/tag/NoCommentInputStream.java
	    modified:   src/org/spdx/tag/SpdxTagValueConstants.properties
	    modified:   src/org/spdx/tag/SpdxViewerConstants.properties
	    modified:   src/org/spdx/tag/TagValueBehavior.java
	    modified:   src/org/spdx/tag/TagValueLexer.smap
	    modified:   src/org/spdx/tag/TagValueParser.smap
	    modified:   src/org/spdx/tag/TagValueParserTokenTypes.java
	    modified:   src/org/spdx/tag/TagValueParserTokenTypes.txt
	    modified:   src/org/spdx/tag/data.g
	    modified:   src/org/spdx/tools/CompareMultpleSpdxDocs.java
	    modified:   src/org/spdx/tools/CompareSpdxDocs.java
	    modified:   src/org/spdx/tools/GenerateVerificationCode.java
	    modified:   src/org/spdx/tools/Main.java
	    modified:   src/org/spdx/tools/MatchingStandardLicenses.java
	    modified:   src/org/spdx/tools/RdfToHtml.java
	    modified:   src/org/spdx/tools/RdfToSpreadsheet.java
	    modified:   src/org/spdx/tools/SpreadsheetToRDF.java
	    modified:   src/org/spdx/tools/SpreadsheetToTag.java
	    modified:   src/org/spdx/tools/TagToSpreadsheet.java

**Comment by romeara** [comment]
@goneall - Confirmed on multiple OS's - this is now resolved

**Comment by kemitchell** [comment]
Great work!
