### ISSUE TITLE
Package Verification Code generated when filesAnalyzed = false

### ISSUE THREAD

**Issue by yevster** [spdx/tools#84]
Per the 2.1 spec, the cardinality of PackageVerificationCode is:

> Mandatory, one if ​**filesAnalyzed**​ is true or omitted,
> Zero (must be omitted) if ​**filesAnalyzed**​ is false.

I added a verification warning for this in #82, which causes a unit test to fail, because PackageVerificationCodes get included even for empty packages with `filesAnalyzed=false`. I'm a bit nervous that this may go too deep for me to tinker with on my own.

**Comment by goneall** [comment]
Fixed and pushed - just a problem in the unit test framework.
