### ISSUE TITLE
Pretty print JSON data files

### ISSUE THREAD

**Issue by dhimmel** [spdx/tools#93]
https://github.com/spdx/license-list-data/blob/master/json/licenses.json (and other JSON files) are currently printed as compact JSON. I think a pretty printed JSON (with newlines and perhaps 2-space indentation) would be better for the following reasons:

+ much easier to visually parse. This makes it easier to work with the JSON file because it becomes more obvious what data it contains.
+ better for git diffs and seeing the changes to the JSON over time

The downside is a slightly larger file size, although I think this is trivial since the file is not large.

**Comment by pombredanne** [comment]
@dhimmel should this be a ticket  for https://github.com/spdx/license-list-data/ instead?

**Comment by dhimmel** [comment]
Ah, I filed it here since I read:

> Note that the content of this repository is generated by the [SPDX tools](http://github.com/spdx/tools) from the [license list source](http://github.com/spdx/license-list).

Happy to migrate this issues to `spdx/license-list` -- just let me know.

**Comment by pombredanne** [comment]
Nope, that's cool. Leave it this way

**Comment by goneall** [comment]
I updated the tool that generates the JSON format to use the GSON pretty printer.

The website and license-list-data will be updated on the next release of the license list.

**Comment by goneall** [comment]
I just pushed the new JSON formats to the license-list-data github repo.  

@dhimmel Please take a look https://github.com/spdx/license-list-data/tree/master/json and let me know if this resolves the issue

**Comment by dhimmel** [comment]
> let me know if this resolves the issue

Yep, resolved in https://github.com/spdx/license-list-data/commit/44eb7cb14a102a092780e6864b6e1c52c3ebcf28. Thanks!
