### ISSUE TITLE
Question: How to parse tag files

### ISSUE THREAD

**Issue by stevespringett** [spdx/tools#94]
I'd like to parse tag-based SPDX files and attempted to use SPDXDocumentFactory.createSpdxDocument thinking it would handle RDF and SPDX files. It appears this only supports RDF. 

I'm unable to find anything that parses a tag file and returns a SpdxDocument. Is the solution to use TagToRDF first, then SPDXDocumentFactory? Any insight would be extremely helpful.

**Comment by pombredanne** [comment]
FWIW, the SPDX Python tools (that I maintain) parse tag/value files alright. I guess they could be bundled as a Java Jar with Jython? TBD.

**Comment by goneall** [comment]
In the tools package there is a static method which will return an SpdxDocument: TagToRDF.convertTagFileToRdf(

                                  InputStream spdxTagFile, String outputFormat, List<String> warnings)

 

The spdxTagFile parameter is a stream containing the tag file.

outputFormat is the format for the RDF/XML – it must be one of RDF/XML-ABBREV, RDF/XML, N-TRIPLET, or TURTLE

**Comment by stevespringett** [comment]
Thank you both for the pointers. @goneall I was able to get it working using the snippet you provided.
