### ISSUE TITLE
license id regex allows `+` chars in middle of license

### ISSUE THREAD

**Issue by timurphy** [spdx/tools#99]
According to the [SDPX specifications](https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60), a license simple expression can only contain the `+` character as the last character. This is tested in this project using the java regex found [here](https://github.com/spdx/tools/blob/02657c72bec23a0f3a2578f6f63e2f0a89235309/src/org/spdx/rdfparser/SpdxRdfConstants.java#L254), which allows the `+` character anywhere in the string.

For example, the license ID `hello+world` would pass the regex mentioned above, however this would be an invalid ID according to the SPDX spec.

**Comment by goneall** [comment]
Good catch - this is definitely a bug.

**Comment by goneall** [comment]
Fixed in source - will be in the 2.1.7 release
